In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC
from sklearn.metrics import classification_report, confusion_matrix

In [2]:
df = pd.read_csv("df_resnet152_features.csv")
ldf = pd.read_csv("final_df_all_images_wo_NF_labels.csv")


In [3]:
cols=[1,2,3,4,5,6,7,8,9,10,11]
ldf.drop(ldf.columns[cols],axis=1,inplace=True)

In [4]:
ldf.drop(ldf.columns[-1],axis=1,inplace=True)

In [6]:
ldf.drop(ldf.columns[0],axis=1,inplace=True)
ldf.head()

Cardiomegaly  Consolidation  Edema  Effusion  Emphysema  Fibrosis  Hernia  \
0             1              0      0         0          0         0       0   
1             1              0      0         0          1         0       0   
2             1              0      0         1          0         0       0   
3             0              0      0         0          0         0       0   
4             0              0      0         0          0         0       1   

   Infiltration  Mass  Nodule  Pleural_Thickening  Pneumonia  Pneumothorax  
0             0     0       0                   0          0             0  
1             0     0       0                   0          0             0  
2             0     0       0                   0          0             0  
3             0     0       0                   0          0             0  
4             0     0       0                   0          0             0

In [7]:
df.drop(['disease_vec'],axis=1)

Unnamed: 0         0         1         2         3         4  \
0                0  1.259055  1.764044  0.074584  0.235642  0.729315   
1                1  0.994248  1.819007  0.115666  0.799520  0.788163   
2                2  1.352075  1.394869  0.021853  0.153628  0.574001   
3                3  1.055545  1.484014  0.090645  0.919076  0.670314   
4                4  1.286834  1.803985  0.310946  0.299076  0.874087   
...            ...       ...       ...       ...       ...       ...   
112115      112115  0.363947  1.365400  0.129166  0.030159  0.612529   
112116      112116  1.061314  0.961209  0.145433  0.222196  0.831245   
112117      112117  1.094563  0.821476  0.097547  0.213494  1.813933   
112118      112118  1.370574  0.833964  0.221878  0.049989  1.740430   
112119      112119  0.887356  0.896695  0.085904  0.307491  0.899014   

               5         6         7         8  ...      2039      2040  \
0       0.108479  1.196721  0.206394  0.257726  ...  0.331340  0.249600   
1       0.404541  1.057724  0.136437  0.008312  ...  0.235418  0.400555   
2       0.191191  1.074452  0.109366  0.518851  ...  0.715820  0.225927   
3       0.278388  0.838380  0.122276  0.055902  ...  0.683062  1.286569   
4       0.582390  1.219509  0.002486  0.211463  ...  0.378083  0.669442   
...          ...       ...       ...       ...  ...       ...       ...   
112115  0.567067  1.102693  0.054730  0.324716  ...  0.538452  0.468761   
112116  0.449361  0.887255  0.059913  0.034677  ...  0.792255  0.303331   
112117  0.460968  1.121084  0.247563  0.159696  ...  0.533410  0.375248   
112118  0.377095  1.341946  0.057433  0.179715  ...  0.353554  0.240670   
112119  0.709190  1.124098  0.184388  0.127936  ...  0.599458  0.234176   

            2041      2042      2043      2044      2045      2046      2047  \
0       0.347991  0.708194  0.719252  1.259327  0.413690  0.642604  0.332446   
1       0.410541  0.943142  1.034511  0.557865  0.322591  0.694101  0.156991   
2       0.175372  1.016153  0.130930  0.748781  0.706917  0.569463  0.600405   
3       0.457071  0.796192  0.366520  1.321119  0.448143  0.465900  0.392211   
4       0.161419  0.766830  0.359261  0.930069  0.317765  0.953285  0.477477   
...          ...       ...       ...       ...       ...       ...       ...   
112115  0.282511  0.715408  0.615525  0.459234  0.235650  0.584656  0.201351   
112116  0.300527  0.870999  0.855485  0.793551  0.314585  0.570017  0.398426   
112117  0.248520  0.991079  1.221894  1.063056  0.032800  0.878712  0.397145   
112118  0.156870  0.807029  1.027311  0.634841  0.317754  0.713152  0.243398   
112119  0.427995  0.702640  0.846942  0.550742  0.168138  0.415642  0.449147   

             image_index  
0       00000001_000.png  
1       00000001_001.png  
2       00000001_002.png  
3       00000002_000.png  
4       00000003_000.png  
...                  ...  
112115  00030801_001.png  
112116  00030802_000.png  
112117  00030803_000.png  
112118  00030804_000.png  
112119  00030805_000.png  

[112120 rows x 2050 columns]

In [8]:
x=df.iloc[:,1:-2]
y=ldf

x.head()


0         1         2         3         4         5         6  \
0  1.259055  1.764044  0.074584  0.235642  0.729315  0.108479  1.196721   
1  0.994248  1.819007  0.115666  0.799520  0.788163  0.404541  1.057724   
2  1.352075  1.394869  0.021853  0.153628  0.574001  0.191191  1.074452   
3  1.055545  1.484014  0.090645  0.919076  0.670314  0.278388  0.838380   
4  1.286834  1.803985  0.310946  0.299076  0.874087  0.582390  1.219509   

          7         8         9  ...      2038      2039      2040      2041  \
0  0.206394  0.257726  1.175031  ...  0.165620  0.331340  0.249600  0.347991   
1  0.136437  0.008312  0.835848  ...  0.180386  0.235418  0.400555  0.410541   
2  0.109366  0.518851  0.965034  ...  0.065134  0.715820  0.225927  0.175372   
3  0.122276  0.055902  1.254084  ...  0.095606  0.683062  1.286569  0.457071   
4  0.002486  0.211463  0.912122  ...  0.111965  0.378083  0.669442  0.161419   

       2042      2043      2044      2045      2046      2047  
0  0.708194  0.719252  1.259327  0.413690  0.642604  0.332446  
1  0.943142  1.034511  0.557865  0.322591  0.694101  0.156991  
2  1.016153  0.130930  0.748781  0.706917  0.569463  0.600405  
3  0.796192  0.366520  1.321119  0.448143  0.465900  0.392211  
4  0.766830  0.359261  0.930069  0.317765  0.953285  0.477477  

[5 rows x 2048 columns]

In [9]:
import numpy as np
from sklearn.multiclass import OneVsRestClassifier
from sklearn.linear_model import LogisticRegression


x_train,x_test, y_train, y_test= train_test_split(x,y,test_size=0.2,random_state = 101)

ovo = OneVsRestClassifier(LogisticRegression())
ovo.fit(x_train, y_train)


/opt/homebrew/anaconda3/lib/python3.8/site-packages/sklearn/linear_model/_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/opt/homebrew/anaconda3/lib/python3.8/site-packages/sklearn/linear_model/_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-re

OneVsRestClassifier(estimator=LogisticRegression())

In [12]:
# to save model 


import joblib

fn='ovolreg.sav'
joblib.dump(ovo, fn)

['ovolreg.sav']

In [13]:
pred = ovo.predict_proba(x_test)
print(pred)

[[0.01142531 0.00427993 0.01020329 ... 0.02270018 0.12010509 0.00656557]
 [0.00279632 0.00744947 0.0041697  ... 0.03428025 0.0183164  0.01408849]
 [0.00093519 0.0101774  0.00042921 ... 0.02806311 0.00125914 0.0208919 ]
 ...
 [0.01368377 0.02546048 0.0083808  ... 0.00390994 0.00305665 0.00725133]
 [0.00235988 0.00928348 0.00021728 ... 0.00971458 0.00333738 0.00323823]
 [0.00768071 0.04353685 0.01524752 ... 0.00579901 0.00718552 0.00309671]]


In [21]:
from sklearn.metrics import roc_auc_score

auc = roc_auc_score(y_test,pred, multi_class='ovo')
print('AUC: %.3f' % auc)

AUC: 0.759
